"""
RAG (Retrieval-Augmented Generation) pipeline for financial queries.
Orchestrates document retrieval and response generation.
"""

from dataclasses import dataclass
from typing import List, Optional, Tuple

from .document_loader import FinancialDocumentLoader
from .vector_store import EmbeddingModel, FinancialVectorStore


@dataclass
class RAGResponse:
    """Structured response from the RAG pipeline."""
    query: str
    answer: str
    sources: List[dict]
    confidence: float
    context_used: int


class FinancialRAGPipeline:
    """End-to-end RAG pipeline for financial document Q&A.

    Architecture:
        Query -> Embedding -> Vector Search -> Context Assembly -> LLM -> Response

    In production, the LLM step calls GPT-4/Claude via LangChain.
    For the POC, a template-based response generator demonstrates the flow.
    """

    def __init__(self, chunk_size: int = 500, chunk_overlap: int = 50, top_k: int = 3):
        self.loader = FinancialDocumentLoader()
        self.embedding_model = EmbeddingModel()
        self.vector_store = FinancialVectorStore()
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.top_k = top_k
        self._is_initialized = False

    @property
    def is_initialized(self) -> bool:
        return self._is_initialized

    def ingest(self, records: List[dict]) -> dict:
        """Ingest financial documents into the pipeline."""
        docs = self.loader.load_from_records(records)
        chunks = self.loader.chunk_documents(
            chunk_size=self.chunk_size, overlap=self.chunk_overlap
        )
        added = self.vector_store.add_chunks(chunks, self.embedding_model)
        self._is_initialized = added > 0
        return {
            "documents_loaded": len(docs),
            "chunks_created": len(chunks),
            "chunks_indexed": added,
        }

    def query(
        self,
        question: str,
        doc_type_filter: Optional[str] = None,
        entity_filter: Optional[str] = None,
    ) -> RAGResponse:
        """Run a RAG query against the financial document store."""
        if not self._is_initialized:
            return RAGResponse(
                query=question,
                answer="Pipeline not initialized. Please ingest documents first.",
                sources=[],
                confidence=0.0,
                context_used=0,
            )

        # Step 1: Retrieve relevant chunks
        results = self.vector_store.search(
            query=question,
            embedding_model=self.embedding_model,
            top_k=self.top_k,
            doc_type_filter=doc_type_filter,
            entity_filter=entity_filter,
        )

        if not results:
            return RAGResponse(
                query=question,
                answer="No relevant documents found for this query.",
                sources=[],
                confidence=0.0,
                context_used=0,
            )

        # Step 2: Assemble context
        context_parts = []
        sources = []
        for meta, score in results:
            context_parts.append(meta["text"])
            sources.append({
                "chunk_id": meta["chunk_id"],
                "doc_id": meta["doc_id"],
                "entity": meta["entity"],
                "doc_type": meta["doc_type"],
                "score": round(score, 4),
            })

        # Step 3: Generate response (template-based for POC; LLM in production)
        context = "\n---\n".join(context_parts)
        answer = self._generate_response(question, context, sources)
        avg_score = sum(s["score"] for s in sources) / len(sources) if sources else 0.0

        return RAGResponse(
            query=question,
            answer=answer,
            sources=sources,
            confidence=round(min(max(avg_score, 0.0), 1.0), 4),
            context_used=len(context_parts),
        )

    def _generate_response(
        self, question: str, context: str, sources: List[dict]
    ) -> str:
        """Generate a response based on retrieved context.

        In production: calls GPT-4/Claude via LangChain with structured prompts.
        POC: template-based response demonstrating the pipeline architecture.
        """
        entities = list(set(s["entity"] for s in sources))
        doc_types = list(set(s["doc_type"] for s in sources))

        response = (
            f"Based on {len(sources)} retrieved document(s) "
            f"covering {', '.join(entities)} "
            f"({', '.join(doc_types)}), "
            f"here is the analysis for your query: '{question}'.\n\n"
            f"Context summary ({len(context)} chars from {len(sources)} chunks):\n"
            f"{context[:500]}{'...' if len(context) > 500 else ''}\n\n"
            f"[In production, this response would be generated by GPT-4/Claude "
            f"via LangChain with the full context and a financial reasoning prompt.]"
        )
        return response

    def get_pipeline_stats(self) -> dict:
        """Return pipeline statistics."""
        return {
            "is_initialized": self._is_initialized,
            "document_stats": self.loader.get_stats(),
            "vector_store_stats": self.vector_store.get_stats(),
            "config": {
                "chunk_size": self.chunk_size,
                "chunk_overlap": self.chunk_overlap,
                "top_k": self.top_k,
            },
        }
